### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by hugovk**
* Just some simple unit tests to be going on with. This'll make it easier to add more in the future, and let's us know if it even runs on different Python versions. Also you see if future PRs break things.

 * Run unit tests on Travis CI. Python 2.6, 2.7, 3.2 3.3, 3.4, 3.5, PyPy and PyPy3 all passIt gives a build report like https://travis-ci.org/hugovk/see/builds/123890089

 * The tests are also run with coverage, which is at 66.67%, and is also sent to Coveralls so you get a report like https://coveralls.io/builds/5827201 where you can see which lines are covered or not.

 * If running tests locally, you can do `python test_see.py` without coverage; or ` coverage run --source=see ./test_see.py -v` with coverage. The `coverage report` shows the results, or `coverage html` to generate local files in htmlcov/

TODO Before merge, please will you enable the araile/see repo at:
 * https://travis-ci.org/profile
 * https://coveralls.io/repos/new
Both are free for open source.

### CODE REVIEW

**Comment by araile** [comment]
Thanks for this. I wasn't sure how to go about unit-testing for this project but this looks like a great start.

I hope to find some time later today to investigate it properly. My initial thoughts:

* I'll look into the services you linked. Travis seems to be a good choice.

* At a glance, coverage/Coveralls seems to ignore the ~100 lines of code that define `SYMBOLS`. Is that right? (I'm not experienced with measuring code coverage, so I'm not sure how this works.)

* There's a lot of stuff added to the .gitignore file. Is much of this needed for testing? I'd rather keep .gitignore to the minimum required for the project.

* If it all works, I'd like to write more unit tests. Would it be possible to put test\_see.py in a *tests* directory and run that directory as a test suite?

**Comment by hugovk** [comment]
> At a glance, coverage/Coveralls seems to ignore the ~100 lines of code that define SYMBOLS. Is that right? (I'm not experienced with measuring code coverage, so I'm not sure how this works.)

Looks like coverage counts `SYMBOLS` as a single, covered line. Line 222 is green (covered), the rest are ignored:
https://coveralls.io/jobs/13671203/source_files/260672864#L222

(The local output of `coverage html` agrees.)

> There's a lot of stuff added to the .gitignore file. Is much of this needed for testing? I'd rather keep .gitignore to the minimum required for the project.

The .gitignore has the common Python things from https://github.com/github/gitignore/blob/master/README.md added, but the least needed for coverage is only  to ignore .coverage and  htmlcov/. Would you like me trim that back down and only add those needed ones?

> If it all works, I'd like to write more unit tests. Would it be possible to put test_see.py in a tests directory and run that directory as a test suite? (Edited to add: would this approach also work with coverage?)

Yes, that's possible, and it also works with coverage. Would you like me to refactor it like that?

**Comment by araile** [comment]
Yes please to the .gitignore and test refactoring. :)

**Comment by araile** [comment]
I've made some changes so that the unit tests and coverage can also be run locally (using `make test`).

I'm happy to merge this in now. Thanks again!

**Comment by hugovk** [comment]
Good stuff, happy to help out!

**Pull request merged**
